using System;
using Terraria.Localization;

namespace Terraria.ModLoader.Config
{
	// Token: 0x0200036F RID: 879
	[Obsolete("Labels are now automatically localized in localization files. Use LabelKeyAttribute to customize the key or use the autogenerated translation key instead. The functionality for showing this field or property in the ModConfig UI despite using [JsonIgnore] is now done through [ShowDespiteJsonIgnoreAttribute]")]
	[AttributeUsage(AttributeTargets.Class | AttributeTargets.Property | AttributeTargets.Field)]
	public class LabelAttribute : Attribute
	{
		// Token: 0x1700058D RID: 1421
		// (get) Token: 0x0600308E RID: 12430 RVA: 0x0053CEE2 File Offset: 0x0053B0E2
		public string Label
		{
			get
			{
				if (!this.label.StartsWith("$"))
				{
					return this.label;
				}
				return Language.GetTextValue(this.label.Substring(1));
			}
		}

		// Token: 0x1700058E RID: 1422
		// (get) Token: 0x0600308F RID: 12431 RVA: 0x0053CF0E File Offset: 0x0053B10E
		public string LocalizationEntry
		{
			get
			{
				if (!this.label.StartsWith("$"))
				{
					return this.label;
				}
				return "{" + this.label + "}";
			}
		}

		// Token: 0x06003090 RID: 12432 RVA: 0x0053CF3E File Offset: 0x0053B13E
		public LabelAttribute(string label)
		{
			this.label = label;
		}

		// Token: 0x04001D19 RID: 7449
		private readonly string label;
	}
}
