using System;
using Terraria.Localization;

namespace Terraria.ModLoader.Config
{
	// Token: 0x02000372 RID: 882
	[Obsolete("Tooltips are now automatically localized in localization files. Use TooltipKeyAttribute to customize the key or use the autogenerated translation key instead.")]
	[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field)]
	public class TooltipAttribute : Attribute
	{
		// Token: 0x1700058F RID: 1423
		// (get) Token: 0x06003093 RID: 12435 RVA: 0x0053CF5F File Offset: 0x0053B15F
		public string Tooltip
		{
			get
			{
				if (!this.tooltip.StartsWith("$"))
				{
					return this.tooltip;
				}
				return Language.GetTextValue(this.tooltip.Substring(1));
			}
		}

		// Token: 0x17000590 RID: 1424
		// (get) Token: 0x06003094 RID: 12436 RVA: 0x0053CF8B File Offset: 0x0053B18B
		public string LocalizationEntry
		{
			get
			{
				if (!this.tooltip.StartsWith("$"))
				{
					return this.tooltip;
				}
				return "{" + this.tooltip + "}";
			}
		}

		// Token: 0x06003095 RID: 12437 RVA: 0x0053CFBB File Offset: 0x0053B1BB
		public TooltipAttribute(string tooltip)
		{
			this.tooltip = tooltip;
		}

		// Token: 0x04001D1A RID: 7450
		private readonly string tooltip;
	}
}
